version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
  url-short:
    build: .
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080" # only export port
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_NAME=docker
      - DB_PORT=5432 # standard postgresql port
